### ISSUE TITLE
MERN V2

### ISSUE THREAD

**Issue by somus** [Hashnode/mern-starter#146]
For the past few weeks, we were busy with the development of Hashnode. That's why couldn't give more time to MERN. We are sorry for those pending issues and pull requests. We will close those issues ASAP. 

In upcoming weeks, we are planning to release the next version of MERN. This is a discussion thread for what should go in MERN v2. I'm adding a rough list of things what we think would be a great addition to MERN. If you think something should not be there or something else should be there, feel free to comment.

- [x] Improve file structure (#90)
- [x] Add PostCSS with CSS Modules (#89)
- [x] Update deps
- [x] Upgrade to webpack 2 and implement tree shaking
- [x] Code splitting with react-router
- [x] Add react-hot-loader 3
- [x] Add ava and enzyme for testing with code coverage (#143)
- [x] Create server bundle for production (#48)
- [x] Commenting code (#39)
- [x] Add docker
- [x] Add react-intl (#54)
- [x] Update documentation

**Note:** I'll be creating a v2 branch, please make all future PRs against that branch.

**Comment by carloscuatin** [comment]
great was waiting for this to start contributing to this great project 👍

**Comment by carloscuatin** [comment]
@somus create branch ? v2.0.0 ?

**Comment by joernroeder** [comment]
One thing I'm currently missing are server-to-server api calls with credentials (cookies) set. I was working on a form with presaved state which wasn't possible on the server and I ended up using an additional request on the client only.

**Comment by somus** [comment]
@carloscuatin Created.

**Comment by SOSANA** [comment]
@somus can we assign @weslleyaraujo  for implementation of postCSS? as mentioned in #89

**Comment by SOSANA** [comment]
@carloscuatin you been assigned anything yet?

**Comment by carloscuatin** [comment]
@SOSANA I'm working on changing the test runner

**Comment by carloscuatin** [comment]
although I think the first thing that will work is the file structure so that is not so difficult to add new updates, we agree that the final structure is proposed by @somus ?

**Comment by somus** [comment]
@SOSANA Definitely. I'm not sure whether to have SASS only or PostCSS only or both with CSS Modules. PostCSS looks like a good option. I'm leaning towards pre-processing with SASS and post-processing with PostCSS. @SOSANA @carloscuatin @weslleyaraujo @Ajar-Ajar @evansendra @raksonibs what do you think?

@evansendra and @raksonibs have done a great job in implementing scss in #50 and #81. But, I think we should import and process scss using webpack. For isomorphic support, as I mentioned above [webpack isomorphic tools](https://github.com/halt-hammerzeit/webpack-isomorphic-tools) looks like a good option.

@carloscuatin You are right. We should first implement the file structure changes. If the option which I proposed in #90 looks good, I'll get on with implementing it. After that, we can target rest of the features in the list.

**Comment by somus** [comment]
@joernroeder You can use something like [express session middleware](https://github.com/expressjs/session) to preserve data on the server side. would this solve your problem?

**Comment by carloscuatin** [comment]
@somus I'm moving in the file structure

**Comment by carloscuatin** [comment]
add react-hot-loader version 3 ?

**Comment by carloscuatin** [comment]
merged in branch v2.0.0 no ?

**Comment by joernroeder** [comment]
@somus yes, i'm using the session middleware right now, the main problem was forwarding the requests from the client to the api route during server-side rendering. 
Imagine the following example: A client with an active session (logged in) requests an api endpoint directly, sends it's stored session via `fetch` with [cookies enabled](https://github.com/github/fetch#sending-cookies), the middleware on the server connects the request to the session and responsd accordingly.
In contrast to the direct client side request is the server the initiator of the `fetch` request during ss-rendering and the cookie value needs to be forwarded from the `client-->server` to the `server-->server` request.

The https://github.com/erikras/react-redux-universal-hot-example claims that:

> Both client and server make calls to load data from separate API server

**Comment by osenvosem** [comment]
Change state management library from Redux to [MobX](https://github.com/mobxjs/mobx) which is much simpler, intuitive and [faster](https://twitter.com/dan_abramov/status/719973322453348352). Demands less boilerplate and code.

**Comment by somus** [comment]
@osenvosem Thanks for the suggestion. :) I've been hearing good things about MobX. We even had an [AMA with MobX creator](https://hashnode.com/ama/with-mobx-cinspo7i500vyxs53buh8ebls) at Hashnode. But, it introduces a couple of new concepts and I'm not sure whether it will be beginner friendly. But, we are planning to make mern-cli clone different versions of mern-starter (more details at Hashnode/mern-cli#10). In future, we can fit in a version with MobX there.

**Comment by osenvosem** [comment]
@somus actually MobX is more beginner friendly that Redux (which is more complicated). You mark your state as `@observable`, you mark react component as `@observer` and that's it. With Redux (and several mandatory libs with it) beginners must learn and write much more.

**Comment by weslleyaraujo** [comment]
@osenvosem I am quite new to MobX, would it play nice with server side render as well? 

good suggestion 💪

**Comment by osenvosem** [comment]
@weslleyaraujo I haven't had a need in that yet, but I saw a couple examples of SSR here on github. [For example](https://github.com/kuuup/mobx-ssr-example)

**Comment by ischyrus** [comment]
Getting code coverage configured and installed as part of the package.

**Comment by SOSANA** [comment]
@osenvosem, open an issue to discuss Mobx so we can keep the discussion and topics related to mern v2

**Comment by hounded** [comment]
could it be possible to adapt the [Ducks](https://github.com/erikras/ducks-modular-redux) methodolgy so that way we can bundle up the functionality we are creating therefore having some kind of module system that would allow the community to develop modules for the mern stack?

**Comment by Ajar-Ajar** [comment]
Any plans to add authentication?
passport, tokens, social OAuth, the real thing... 
I think it's a pretty basic... every application needs one,
and it's not trivial how to set it up in Mern...

**Comment by somus** [comment]
@Ajar-Ajar There are a lot of ways to include auth. There is no single universal way to do it. We don't want to add one single method in mern-starter. That's why we are going to make mern-cli clone variants of mern. One of the variants can have social auth, and other can have jwt auth. Through this way, the possibilities are infinite. We are looking to modify mern-cli with this week to make it possible.

**Comment by Ajar-Ajar** [comment]
Sounds exciting!!!

**Comment by mayankchd** [comment]
Tree shaking and code splitting with react-router is super super cool!

**Comment by koshuang** [comment]
Good job for you guys. Just wondering if you have any plans about using redux-saga?
Thanks!

**Comment by somus** [comment]
V2 is released. 🎆 📢 🍻 😸 
We have also updated [mern.io](http://mern.io). Check it out.

**Comment by devourment77** [comment]
I know this is closed, but just curious if anyone made or is making a mobx version. I did a mern-cli list but it didn't look like anyone published a variant.
